apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-details-ms
  labels:
    app: all-details-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: all-details-microservice
  template:
    metadata:
      labels:
        app: all-details-microservice
    spec:
      containers:
        - image: kiranbs13/all-details-micro:lastest
          name: all-details-microservice
          ports:
            - containerPort: 9000
